apps/noticias/urls.py
from django.urls import path
from . import views

#LA URL SIEMPRE EMPIEZA CON /Noticias en este archivo, pero solo va a funcionar en la url si su direccion es /Noticias/Listar ya que /Noticias me direcciona a urls de la apps noticias, pero en esta la que me direcciona al html es /Listar

app_name = 'noticias' #aca lo que le digo es que en la url para esta aplicacion se va a llamar noticias

urlpatterns = [
    path('listar/', views.Listar, name = 'listar_noticias'), #el listar/ es solo el string que aparece en la url, el views.Listar es el nombre de la app, y el listar_noticias es como lo vamos a llamar a la vista desde otra vista o pagina

    #PARA MOSTAR EL PATH CON LA VISTA BASADA EN CLASE
    path('detalle/<int:pk>', views.Detalle_Noticia_Clase.as_view(), name = 'detalle_noticia')




    # ASI ES PARA MOSTRAR HACIENDO CON LA FUNCION --> path('detalle/<int:pk>', views.Detalle_Noticia, name = 'detalle_noticia'), #para que me lleve a una determinada noticia tengo que decirle a la url que este preparada para recibir un dato. Entonces va a recibir un entero int que va a recibir una variable que se llama pk. se representa con <> 
    # el pk lo va a recibir la lista en la funcion detalle_noticia como parametro
    #de forma predeterminada django llama pk a la clave primaria
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static #estas dos importaciones son para que la imagen aparezca en la pagina
from django.conf import settings 

#URL LOGIN
from django.contrib.auth import views as auth

from . import views #de la misma carpeta en la que estoy importar el archivo views
urlpatterns = [
    path('admin/', admin.site.urls), #para crear el superusuario o admin es python manage.py createsuperuser
    #URL PRINCIPAL
    path('',views.Home, name = 'home'), #url para el home, significa que si viene vacio '' entonces me direcciona hacia el home

    #agrego el path del login
    path('login/',auth.LoginView.as_view(template_name = 'usuarios/login.html'), name = 'login'),
    path('logout/',auth.LogoutView.as_view(), name = 'logout'),

    #URL DE APLICACIONES
    path('Noticias/',include('apps.noticias.urls')), # siempre que venga en el url noticias me redirecciona hacia mi apps de noticias
] + static (settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #ESTO VA CON LAS DOS IMPORTACIONES QUE AGREGAMOS ULTIMAS PARA QUE SE VISUALICE LA IMAGEN (va en la llave que ciera url patterns)

apps/noticias/models.py
from django.db import models

# Create your models here.

# es como que la clase noticia esta heredando de models.model
#siempre que yo pongo algo en el archivo model debo migrar para que impacte en la bd, esto se hace con python manage.py makemigrations y luego python manage.py migrate


#-------> SIEMPRE QUE MODIFICO EL MODEL DEBO MIGRAR   <---------------------

#PARA QUE UN TIPO DE DATO SEA DESPLEGABLE Y EVITAR TIPOS DE ERRORES, COMO EN ESTE CASO CATEGORIA, LO QUE DEBEMOS HACER ES HACERLO UNA CLASE

class Categoria(models.Model):
    nombre = models.CharField(max_length=60)
    descripcion = models.CharField(max_length=250, null=True, blank = True)

    def __str__(self):
        return self.nombre


class Noticia(models.Model): #model.Model siempre va es una clase de django y es el que me transforma la clase noticia en una clase que va a utilizar la ORM de django
    titulo = models.CharField(max_length = 120) #para caracter es models.Charfield(max_length que seria maximo tamaño)
    creado = models.DateField(auto_now_add=True) # el parametro en true es que va a guardar la fecha en la que es modificado o subido automaticamente
    cuerpo = models.TextField() #es para textos largos que no tienen definicion de caracteres, no tiene parametros
    autor = models.CharField(max_length = 50, null = True, blank = True) #es para que me aceptee cuando cargo una noticia en blanco) #el null true es como en base de datos que permite valores nulos, es decir, que no es obligatorio que contenga algo
    imagen = models.ImageField(upload_to = 'noticias', null = True, blank = True) #Lo que le estoy diciendo es que la imagen se guardara en noticias
    categoria = models.ForeignKey(Categoria, on_delete= models.CASCADE, null=True) #ACA LA RELACION SERIA QUE UNA RELACION PERTENECE A UNA CATEGORIA Y UNA CATEGORIA PUEDE ESTAR EN MUCHAS NOTICIAS, ENTONCES LA FOREINGKEY VA EN NOTICIAS
    #categoria dice que la noticia va a tener un campo categoria que va a ser una clave foranea a la clase categoria y el on delete significa que pasa si borro la categoria, ES DECIR QUE SI BORRO UN TIPO DE CATEGORIA SE VAN A BORRAR TODAS LAS NOTICIAS ASOCIADAS A ESA
    #cuando hago el migrations de categoria salta un error porque ya tengo noticias cargadas y no tengo categorias todavia, entonces debo agregar el null true, sino no hay forma
    #generalmente las claves foraneas se ponen al empezar el trabajo y sino la unica solucion es poner que sean nulas
    #y si da un error por haber cargado la migracion sin el null lo que se debe hacer es borrar la ultima migracion de la carpeta migrations 
#para las imagenes debemos instalar la libreria pillow, sino no va a funcionar. se instala en el entorno poniendo pip install pillow

    def __str__(self): #debe ir dentro de la clase nombrada, sino no funciona
        return self.titulo # va a mostrar el nombre de los titulos

apps/usuarios/models.py
from django.db import models

# Create your models here.
#aca van a estar los modelos que van a impactar en la base de datos 

from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    pass

apps/noticias/views.py
from django.shortcuts import render

#importo las librerias para hacer la vista basada en clase
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


from . models import Noticia #siempre debo importar
# Create your views here.

def Listar(request): #VISTA BASADA EN FUNCIONES
    #Para mostrar las noticias en la pagina se crea un diccionario que se lo encuentra comunmente llamado como contexto (ctx)
    ctx = {} #creo el diccionario para pasar datos al template
    #BUSCO LO QUE QUIERO EN LA BD
    todas = Noticia.objects.all()
    print(todas) #para saber que lo de arriba anda hacemos un print
    #PASARLO AL TEMPLATE
    ctx['notis'] = todas
    return render(request,'noticias/listar_noticias.html', ctx) #aca lo que le digo es que el html se va a encontrar dentro de la carpeta noticias y se utiliza / para señalar

#parte de traer las noticias o datos de la bd como lo hacemos nosotros, url luego vista y luego el template. Existe algo que se llama vistas basadas en clases 

class Detalle_Noticia_Clase(DetailView): #VISTA BASADA EN CLASE
    model = Noticia
    template_name = 'noticias/detalle_noticia.html'
#SI USO UNA VISTA BASADA EN CLASE EL CONTEXTO SE LE LLAMA:
#SI ES UNO SOLO object
#SI SON MUCHOS SE LLAMA object_list



''' ASI MOSTRARIA EL DETALLE DE CADA NOTICIA, PERO VOY A PROBAR HACIENDO CON LA VISTA BASADA EN CLASE
def Detalle_Noticia(request, pk):
    #una vez que tengo esa pk tengo que capturarla en un diccionario como ya hicimos en listar y pasarla a detalle noticia
    ctx = {}
    noticia = Noticia.objects.get(pk = pk) #aca coincide que los dos se llaman pk pero a la variable que nosotros la llamamos asi podemos cambiarla
    ctx['resultado'] = noticia
    return render(request,'noticias/detalle_noticia.html',ctx )'''





''' PARA QUE ME TRAIGA TODAS LAS NOTICIAS SE HACE A TRAVES DE LA ORM

Los tipos de consulta que vamos a usar son:

Nombre.Modelo.objects.get(id = myID) --> se usa si estoy seguro que el resultado es un solo objeto, es decir filtra por clave, el resultado va a ser un solo registro

Nombre.Modelo.objects.filter(campo1 = myfiltro1, campo2 = myfiltro2)  -->  este lo que hace es traerme todos los que sean iguales

Nombre.Modelo.objects.all()  --> este seria un select*from'''


#EJEMPLO DE COMO DESARMA EL CTX EL TEMPLATE
#ctx['nombre'] = 'nicolas'
#ctx['notas'] = [5,6,9]
#EL TEMPLATE ya separa el diccionario
#nombre = 'nicolas'
#notas = [5,6,9]

apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render

def Home(request):
    return render(request,'home.html') #retorna el html que se llama home

templates/base.html
{% load static %}
<!-- el load static te carga todos los archivos estaticos -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BLOG</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>

    <!-- MENU -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <button type="button" class="btn btn-outline-primary" style="margin-right:15px">
                <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            </button>
            <button type="button" class="btn btn-outline-primary" style="margin-right:40px">
                <a class="navbar-brand" href="{% url 'noticias:listar_noticias' %}">Noticias</a>
            </button>
            {% if user.is_authenticated %}
                <a class="navbar-brand" href="#">Hola {{user.username}}!!</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <!--Lo que me hace el ms-auto es mandarme a la izquierda la barra de navegacion por defecto,  -->
                    <button type="button" class="btn btn-outline-primary">
                        <li class="nav-item">
                            <a class="navbar-brand" href="{% url 'logout' %}">Salir</a>
                        </li>
                    </button>
                </ul>
                </div>
            {% else %}
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <!--Lo que me hace el ms-auto es mandarme a la izquierda la barra de navegacion por defecto,  -->
                    <button type="button" class="btn btn-outline-primary">
                        <li class="nav-item">
                            <a class="navbar-brand" href="{% url 'login' %}">Login</a>
                        </li>
                    </button>
                </ul>
                </div>
            {% endif %}
        </div>
        </nav>

    <!--FIN MENU -->
    {% block contenido %}

    {% endblock contenido %}
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
<!-- El extends siempre va primero -->
{% extends 'base.html' %}
{% load static %}


{% block contenido %}

    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'img/imagen1.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
            <h5>Etiqueta de la primera diapositiva</h5>
            <p>Algún contenido placeholder representativo para la primera diapositiva.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'img/imagen2.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
            <h5>Etiqueta de la segunda diapositiva</h5>
            <p>Algún contenido placeholder representativo para la segunda diapositiva.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'img/imagen3.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
            <h5>Etiqueta de la tercera diapositiva</h5>
            <p>Algún contenido placeholder representativo para la tercera diapositiva.</p>
            </div>
        </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Anterior</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Siguiente</span>
        </button>
    </div>

{% endblock %}

templates/noticias/detalle_noticia.html
{% extends 'base.html' %}
{% load static %}

    {% block contenido %}
    <br><br>
        <h1>{{object.titulo}}</h1> <br><br>
        <!--Por ultimo para mostrar con la vista basada en clase en vez de poner el nombre de la lista ej resultado, n, se pone object que seria el objeto de la clase-->
            {% if object.imagen %}
                <img src="{{ object.imagen.url }}" width = "300px" height = "300px">
            {% endif%}
            <h2>{{object.cuerpo}}</h2>
        
    {% endblock contenido %} 

templates/noticias/listar_noticias.html
{% extends 'base.html' %}
{% load static %}

<!-- como son objetos para acceder a sus campos seria a traves de puntos, ej en categoria para acceder a su descripcion seria n.categoria.descripcion -->
<!-- Se usa {%% cuando es una accion, for if, etc y {{} es cuando es una variable y hay que mostrar su contenido -->
    {% block contenido %}

        <h1> NOTICIAS ACTUALES</h1>
        <br>
        <br>
        <div class="container mx-10">
        <div class="row row-cols-10 row-cols-md-5 g-4">
            {% for n in notis %}
                            <div class="card" style= "width:300px"; height ="200px">
                                <div class="container py-3">
                                    <div class="header">
                                        {% if n.imagen %}
                                            <img class="card-img-top" src="{{ n.imagen.url }}" width = "100%" height = "350px">
                                        {% endif%}
                                        <div class="card-body">
                                            <h5 class="card-title">{{ n.titulo}}</h5>
                                            <p class="card-text">{{n.cuerpo}}</p>
                                            <a href="{% url 'noticias:detalle_noticia' n.pk %}" class="btn btn-primary">Ver más</a>
                                            <!--Luego de pasarle por parametro la variable llamada pk, tengo que ponerla en el url para que me redireccione a la misma noticia-->
                                        </div>
                                    </div>
                                </div>
                            </div>          
            {% endfor %}
        </div>
        </div>
    {% endblock contenido %} 
<!-- para mostrar una imagen se usa img con el doble corchete y el .url es algo que se pone por defecto que hace transformar esa imagen en una url valida -->

templates/usuarios/login.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}

    <div class="container w-75 mt-5 rounded shadow bg-light">
        
                    <img src="{% static 'img/logo.png'%}" width="55px">
                <h2 class=" text-center py-2">Bienvenido</h2>
            <form method="POST"> {%csrf_token%} 
                {{form.errors}} 
                <form action="#">
                    <div class="mb-4">
                        <label for="email" class="form-label">Usuario</label>
                        <input type="text" name = "username" class = "form-control">
                    </div>
                    <div class="mb-4">
                        <label for="password" class="form-label">Contraseña</label>
                        <input type="password" class = "form-control" name="password">
                    </div>
                    <div class="mb-4">
                        <input type="checkbox" name="connected" class = "form-check-input">
                        <label for="connected" class="form-check-label">Mantenerme conectado</label>
                    </div>
                    <div class="d-grid">
                        <button type="submit" class = "btn btn-primary">Iniciar Sesión</button>
                    </div>

                    <div class="my-3">
                        <span>No tienes cuenta? <a href="#">Registrate</a> </span>
                        <span><a href="#">Recuperar Contraseña</a></span>
                    </div>
                </form>
            </form>
                <!--Login con redes sociales-->

                <div class="container w-100 my-5">
                    <div class="row text-center">
                        <div class="col-12"></div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <button class="btn btn-outline-primary w-100 my-1">
                                <div class="row align-items-center">
                                    <div class="col-2 d-none d-md-block">
                                        <img src="{% static 'img/face.png'%}" width="32">
                                    </div>
                                    <div class="col-12 col-md-10 text-center">
                                        Facebook
                                    </div>
                                </div>
                            </button>
                        </div>
                        <div class="col">
                            <button class="btn btn-outline-danger w-100 my-1">
                                <div class="row align-items-center">
                                    <div class="col-2 d-none d-md-block">
                                        <img src="{% static 'img/google.png'%}" width="32">
                                    </div>
                                    <div class="col-12 col-md-10 text-center">
                                        Google
                                    </div>
                                </div>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}